Trying linear execution

diff --git a/.github/workflows/taxi_draft.yml b/.github/workflows/taxi_draft.yml
--- a/.github/workflows/taxi_draft.yml
+++ b/.github/workflows/taxi_draft.yml
@@ -20,12 +20,20 @@ env: # This should be a set of github secrets
   USER_GCP_ZONE: us-central1-a
   REPO_URL: https://repository.apache.org/content/repositories/orgapachebeam-1284
 jobs:
-  sql_taxi_with_dataflow:
+  python_cross_validation:
     runs-on: [self-hosted,ubuntu-20.04]
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
-
+    - name: Common tasks
+      uses: ./.github/actions/common-rc-validation
+    - name: Verify ENV values
+      run: |
+        echo ""
+        echo "====================Checking Environment & Variables================="
+        echo ""
+        echo "running validations on release ${{github.event.inputs.RELEASE_VER}} RC${{github.event.inputs.RC_NUM}}."
+        echo "repo URL for this RC: $GIT_REPO_URL"
     - name: Install Kubectl 
       uses: azure/setup-kubectl@v3
 
@@ -40,14 +48,44 @@ jobs:
       with:
         python-version: '3.8'
         cache: 'pip' # caching pip dependencies
-    
-    - name: Setting python env
-      uses: ./.github/actions/common-rc-validation
+    - name: Downloading Python Staging RC
+      run: |
+        echo ""
+        echo "====================Starting Python Cross-language Validations==============="
+  
 
+        echo "---------------------Downloading Python Staging RC----------------------------"
+        wget ${PYTHON_RC_DOWNLOAD_URL}/${RELEASE_VER}/python/apache-beam-${RELEASE_VER}.zip
+        wget ${PYTHON_RC_DOWNLOAD_URL}/${RELEASE_VER}/python/apache-beam-${RELEASE_VER}.zip.sha512
+        if [[ ! -f apache-beam-$RELEASE_VER.zip ]]; then
+          { echo "Fail to download Python Staging RC files." ;exit 1; }
+        fi
+
+        echo "--------------------------Verifying Hashes------------------------------------"
+        sha512sum -c apache-beam-${RELEASE_VER}.zip.sha512
+
+        `which pip` install --upgrade pip
+        `which pip` install --upgrade setuptools
+
+        KAFKA_CLUSTER_NAME=xlang-kafka-cluster-$RANDOM
     - name: Installing gcloud-auth-plugin
       run: sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
-
-
+    - name: Setting Kafka Cluster Name # TODO: change to random again once the tests are finished
+      run: |
+        echo "KAFKA_CLUSTER_NAME=xlang-kafka-cluster-12817">> $GITHUB_ENV 
+#    - name: Creating Kafka Cluster
+#      run: |
+#        gcloud container clusters create --project=${USER_GCP_PROJECT} --region=${USER_GCP_REGION} --no-enable-ip-alias $KAFKA_CLUSTER_NAME
+#        kubectl apply -R -f .test-infra/kubernetes/kafka-cluster
+    - name: Getting cluster credentials
+      run: gcloud container clusters get-credentials ${KAFKA_CLUSTER_NAME} --region ${USER_GCP_REGION} --project ${USER_GCP_PROJECT}
+    - name: Setting Python Environment
+      run: |
+        echo "--------------------------Installing Python SDK-------------------------------"
+        pip install --upgrade pip setuptools wheel
+        pip install apache-beam-${RELEASE_VER}.zip[gcp]
+    - name: Waiting for Kafka cluster to be ready
+      run: kubectl wait --for=condition=Ready pod/kafka-0 --timeout=900s
     - name: Setting Taxi Variables
       run: |
         echo "SQL_TAXI_TOPIC=${GITHUB_ACTOR}_python_validations_$(date +%m%d)_$RANDOM" >> $GITHUB_ENV
@@ -71,12 +109,9 @@ jobs:
         --output_topic projects/${USER_GCP_PROJECT}/topics/${SQL_TAXI_TOPIC} \
         --beam_services="{\":sdks:java:extensions:sql:expansion-service:shadowJar\": \"${SQL_EXPANSION_SERVICE_JAR}\"}" \
         --sdk_location apache-beam-${RELEASE_VER}.zip || true
-    - name: Checking results
-      run: |
-        gcloud pubsub subscriptions pull --project=${USER_GCP_PROJECT} --limit=5 ${SQL_TAXI_SUBSCRIPTION}
-    - name: Removing Pub/Sub Topics
-      if: always()
-      run: |
-        gcloud pubsub topics delete --project=${USER_GCP_PROJECT} ${SQL_TAXI_TOPIC}
-        gcloud pubsub subscriptions delete --project=${USER_GCP_PROJECT} ${SQL_TAXI_SUBSCRIPTION}
-  
+#    - name: Checking results
+#    - name: Removing Pub/Sub Topics
+#      if: always()
+#      run: |
+#        gcloud pubsub topics delete --project=${USER_GCP_PROJECT} ${SQL_TAXI_TOPIC}
+#        gcloud pubsub subscriptions delete --project=${USER_GCP_PROJECT} ${SQL_TAXI_SUBSCRIPTION}
